---
# Probably can benefit from check before (register)
# to execute conditionally
- name: Verify Helm list
  become: true
  become_user: "{{ nemesis_server_username }}"
  ansible.builtin.command: helm list -A
  register: quickstart_check
  changed_when: false

- name: Install Elastic operator
  become: true
  become_user: "{{ nemesis_server_username }}"
  ansible.builtin.command: >
    helm install elastic-operator eck-operator
    --repo https://helm.elastic.co
    --namespace elastic-system
    --create-namespace
    --set managedNamespaces='{default}'
  when: "'elastic-operator' not in quickstart_check.stdout"
  changed_when: "'elastic-operator' not in quickstart_check.stdout"

- name: Wait for traefik to finalize
  ansible.builtin.pause:
    seconds: 60
  when: "'traefik' not in quickstart_check.stdout"
  changed_when: "'traefik' not in quickstart_check.stdout"

- name: Write user input to file
  become: true
  become_user: "{{ nemesis_server_username }}"
  ansible.builtin.template:
    src: quickstart-values.yaml.j2
    dest: /home/{{ nemesis_server_username }}/quickstart-values.yaml
    mode: '0644'

- name: Run quickstart chart if not already installed
  become: true
  become_user: "{{ nemesis_server_username }}"
  ansible.builtin.command: >
    helm install --repo https://specterops.github.io/Nemesis/ nemesis-quickstart quickstart -f /home/{{ nemesis_server_username }}/quickstart-values.yaml
  when: "'quickstart' not in quickstart_check.stdout"
  changed_when: "'quickstart' not in quickstart_check.stdout"
